<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net7.0-android</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.GoogleAds.Mediation.AppLovinAdapter</PackageId>
		<PackageVersion>12.1.0.1</PackageVersion>
		<AssemblyVersion>12.1.0.1</AssemblyVersion>
		<FileVersion>12.1.0.1</FileVersion>
		<Version>12.1.0.1</Version>
		<Title>Anjo Android AppLovin Mediation Adapter For The Google Mobile Ads SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.GoogleAds.Mediation</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) bindings for Google Play Services library 'com.google.ads.mediation:applovin'.</Description>
		<PackageReleaseNotes>AppLovin Mediation Adapter For The Google Mobile Ads SDK v12.1.0.1</PackageReleaseNotes>
		<Copyright>Copyright (c) 2024 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, Mediation, GoogleAdsMediation, AppLovin, AppLovinAdapter</PackageTags>
		<Summary>The AppLovin mediation adapter is a library that handles communication between the Google Mobile Ads SDK and the AppLovin SDK. It enables you to load ads from AppLovin using the mediation feature in the Google Mobile Ads SDK.</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="Jars\applovin-12.1.0.1.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup> 
	<ItemGroup>
		<PackageReference Include="Anjo.Android.AppLovin" Version="12.2.0" />
		<PackageReference Include="Anjo.Android.GoogleServices.Ads" Version="22.6.0" />
		<PackageReference Include="Xamarin.AndroidX.Annotation" Version="1.7.1.1" />
	</ItemGroup>
</Project>